apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-map
data:
  DB_URL: postgresql+psycopg2://<USERNAME>:<PASSWORD>@<SVC_NAME>.<NAMESPACE>:<DATABASE_PORT>/<DATABASE_NAME>
  SERVER_PORT: "5000"
  SERVER_HOST: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    type: app
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      labels:
        type: app
    spec:
      containers:
      - name: app-container
        image: <YOUR_APP_IMAGE>
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 60
          failureThreshold: 3
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: app-config-map
