# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: postgress-pv
#   labels:
#     user: postgress
# spec:
#   storageClassName: standard 
#   capacity:
#     storage: 2Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce 
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: "/home/amontasser/data"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgress-pvc
# spec:
#   resources:
#     requests:
#       storage: 2Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
# ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgress-config-map
data:
  POSTGRES_DB: mydb
---
apiVersion: v1
kind: Secret
metadata:
  name: postgress-secret
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: ZGlubw==
---
apiVersion: v1
kind: Service
metadata:
  name: postgress-service
spec:
  ports:
  - port: 5432
    name: postgress-port
    protocol: TCP
  clusterIP: None
  selector:
    type: postgress
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgress-sts
spec:
  replicas: 2
  selector:
    matchLabels:
      type: postgress
  serviceName: postgress-service
  template:
    metadata:
      labels:
        type: postgress
    spec:
      containers:
      - name: postgress-container
        image: postgres:16
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgress-config-map
        - secretRef:
            name: postgress-secret
        volumeMounts:
          - name: postgress-data
            mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgress-data
    spec:
      accessModes: [ "ReadWriteOncePod" ]
      resources:
        requests:
          storage: 1Gi
