version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres-container
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  bus_app:
    build: .
    # image: ahmedmontasser/backend:busV1
    container_name: bus_app
    ports:
      - "5000:5000"
    working_dir: /bus_app
    environment:
      SERVER_PORT: 5000
      SERVER_HOST: 0.0.0.0
      APP_NAME: bus_app
    depends_on:
      db:
        condition: service_healthy

  # bus_app2:
  #   image: ahmedmontasser/backend:busV1
  #   container_name: bus_app2
  #   ports:
  #     - "7000:7000"
  #   working_dir: /bus_app
  #   environment:
  #     SERVER_PORT: 7000
  #     SERVER_HOST: 0.0.0.0
  #     APP_NAME: bus_app
  #   depends_on:
  #     db:
  #       condition: service_healthy


  microbus_app:
    build: .
    container_name: microbus_app
    ports:
      - "7000:7000"
    working_dir: /microbus_app
    environment:
      SERVER_PORT: 7000
      SERVER_HOST: 0.0.0.0
      APP_NAME: microbus_app
    depends_on:
      db:
        condition: service_healthy

  # Trainging the Nginx container to serve as a reverse proxy for the bus_app and bus_app2 services
#   nginx:
#     build:
#       context: ./nginx_app
#       dockerfile: nginx.dockerfile
#     container_name: nginx-container
#     ports:
#       - "80:80"
#       - "443:443"
#     depends_on:
#       - bus_app
#       - bus_app2

volumes:
  pgdata:
